---
baseURL: http://example.org/
languageCode: en-us
title: Dioscorides | Herbs
theme: hugo-fresh
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  openGraph: true
  description: 
  navbarlogo:
    image: logos/logo-lg.png
    link: "/"
    width: 112
    height: 112
  font:
    name: Open Sans
    sizes:
    - 400
    - 600
  hero:
    title: Our mission
    subtitle: is to promote the use of natural products that are effective in preserving
      and improving health and well-being, as well as in combating aging and health
      conditions.
    image: homepage/dioscorides-home-page.jpg
  navbar:
  - title: Blog
    url: "/blog/"
  - title: About Dioscorides
    url: "/about/"
  - title: Contact
    url: "/#section5"
  - title: Donate Us
    url: "/donate/"
    button: true
  sidebar:
    logo: logo-sm.png
    sections:
    - title: Featured Articles
      icon: newspaper-o
      links:
      - text: First Blog Post
        url: "/blog/first/"
      - text: Second Blog Post
        url: "/blog/second/"

  section5: true
  footer:
    logo: logo-lg.png
    bulmalogo: true
    quicklinks:
      # column1:
      #   title: Blog
      #   links:
      #   - text: First Blog Article
      #     link: "/blog/first/"
      #   - text: First Blog Article
      #     link: "/blog/second/"
      column3:
        title: Legal
        links:
        - text: Disclaimer
          link: "/disclaimer"
        - text: Privacy Policy
          link: "/privacy-policy"
googleAnalytics: 
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
